# Generated by Django 3.1 on 2022-05-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Before started'), ('2', 'On going'), ('3', 'Finished')], default='1', max_length=40),
        ),
    ]
